baseURL = '/'
locale = 'en-us'
title = 'KIPR Docs'
disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']

[markup.highlight]
# emit CSS classes, not inline styles
noClasses = false
lineNos = false

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[params]
recommended_wombatos_version = "31.2.0"
